import type { Metadata } from "next";
import { sourceSans } from "./fonts"
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata: Metadata = {
  title: "To Do List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${sourceSans.className} h-full antialiased`}
    >
      <TooltipProvider>
        <body className="min-h-full flex flex-col">{children}</body>
      </TooltipProvider>
    </html>
  );
}
